export enum VehicleBrands {
   AUDI = 1,
   BMW = 2,
   BYD = 3,
   CHERY = 4,
   CHEVROLET = 5,
   CITROEN = 6,
   FIAT = 7,
   FORD = 8,
   HONDA = 9,
   HYUNDAI = 10,
   JAC = 11,
   JEEP = 12,
   KIA = 13,
   LAND_ROVER = 14,
   MERCEDES_BENZ = 15,
   MITSUBISHI = 16,
   NISSAN = 17,
   PEUGEOT = 18,
   RENAULT = 19,
   SUBARU = 20,
   SUZUKI = 21,
   TESLA = 22,
   TOYOTA = 23,
   VOLKSWAGEN = 24,
   VOLVO = 25,
   OTHER = 26,
}
