export enum VehicleBrands {
   AUDI = "Audi",
   BMW = "BMW",
   BYD = "BYD",
   CHERY = "Chery",
   CHEVROLET = "Chevrolet",
   CITROEN = "Citroen",
   FIAT = "Fiat",
   FORD = "Ford",
   HONDA = "Honda",
   HYUNDAI = "Hyundai",
   JAC = "JAC",
   JEEP = "Jeep",
   KIA = "Kia",
   LAND_ROVER = "Land Rover",
   MERCEDES_BENZ = "Mercedes-Benz",
   MITSUBISHI = "Mitsubishi",
   NISSAN = "Nissan",
   PEUGEOT = "Peugeot",
   RENAULT = "Renault",
   SUBARU = "Subaru",
   SUZUKI = "Suzuki",
   TESLA = "Tesla",
   TOYOTA = "Toyota",
   VOLKSWAGEN = "Volkswagen",
   VOLVO = "Volvo",
   OTHER = "Other",
}
